name: Markdown Accessibility
description: Suggests alt text for images in markdown files
branding:
  icon: image
  color: purple

inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Suggest Alt Text
      run: |
        python ${{ github.action_path }}/alt_text.py
      shell: bash
