name: Markdown Accessibility
description: Suggests alt text for images in markdown files
branding:
  icon: image
  color: purple

inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}

  azure_key:
    description: "Azure Computer Vision API key"
    required: false

  azure_endpoint:
    description: "Azure Computer Vision API endpoint"
    required: false

  language:
    description: "Language to use for alt text suggestions"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v2

    - name: Check Alt Text
      id: alt_text_checker
      run: |
        python ${{ github.action_path }}/alt_text_checker.py
      shell: bash

    - name: Install dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Suggest Alt Text
      run: |
        python ${{ github.action_path }}/alt_text.py ${{inputs.token}} ${{inputs.azure_key}} ${{inputs.azure_endpoint}} ${{inputs.language}}
      shell: bash

    - uses: DavidAnson/markdownlint-cli2-action@v10
      continue-on-error: true
      with:
        command: fix
        globs: "**/*.md"
