name: Markdown Accessibility
description: Suggests alt text for images in markdown files
branding:
  icon: image
  color: purple

on:
  workflow_dispatch:
    inputs:
      token:
        description: "GitHub token"
        required: true

jobs:
  suggest_alt_text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Suggest Alt Text
        run: python alt_text.py ${{ inputs.token }}
