name: Markdown Accessibility Helper

on:
  workflow_dispatch:

jobs:
  suggest_alt_text:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Suggest Alt Text
        run: python alt_text.py
        with:
          token: ${{secrets.GITHUB_TOKEN}}
