name: My Workflow

# Runs only when triggered manually

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Markdown Accessibility
        uses: sam9111/markdown-accessibility-helper@test-lint
